{# Loop the css file array and write the <link> tags into the header #}
{# Only hard code any bower css files that ref other files, eg the icons ionicons. Anything else, copy and paste their css into a bower_overrides
     file. This is to limit the qty of files the end client must download in production, speeding things up#}
{# When updating the bower, should you want any additional css, make sure you copy it from bower into the respective bower override scss #}
{# !important: when added new css, ensure to retain previous changes, eg the ngdialog overrides for z-index and commented out bits #}

{% set cssFiles = [
    '/css/all.css',
    '/bower_components/font-awesome/css/font-awesome.css',
    '/bower_components/bootstrap/dist/css/bootstrap.min.css'
] %}
{% for cssFile in cssFiles %}       <link href="{[ cssFile ]}" rel="stylesheet">
{% endfor %}